import React,{useState}from"react";
import{router}from"expo-router";import{SafeAreaView,ScrollView,View,Text,Pressable,TextInput,StyleSheet}from"react-native";import{messages,type Locale}from"@sevamitra/i18n";
const services=["🏠 Cleaning","⚡ Electrician","🔧 Plumber","✨ Beauty","👴 Elder Care","⚙️ Appliance","📚 Tutors","••• More"];
export default function Home(){const[locale,setLocale]=useState<Locale>("kn");const t=messages[locale];return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}>
 <View style={s.header}><View><Text style={s.logo}>Seva<Text style={s.orange}>Mitra</Text></Text><Text style={s.tag}>Local Services. Stronger Communities.</Text></View><Pressable style={s.lang} onPress={()=>setLocale(locale==="kn"?"en":"kn")}><Text>{locale==="kn"?"EN":"ಕನ್ನಡ"}</Text></Pressable></View>
 <View style={{flexDirection:"row",gap:12,marginHorizontal:20,marginVertical:6}}>
  <Pressable style={{padding:12,borderRadius:12,backgroundColor:"#087A4B"}} onPress={()=>router.push("/login")}>
   <Text style={{color:"#fff",fontWeight:"800"}}>Sign in / Login</Text>
  </Pressable>
  <Pressable style={{padding:12,borderRadius:12,backgroundColor:"#E3F2EA"}} onPress={()=>router.push("/workspaces")}>
   <Text style={{color:"#075C40",fontWeight:"800"}}>My workspaces →</Text>
  </Pressable>
 </View>
 <View style={s.hero}><Text style={s.badge}>{t.hero.badge}</Text><Text style={s.title}>{t.hero.title1}{"\n"}<Text style={s.green}>{t.hero.title2}</Text></Text><Text style={s.subtitle}>{t.hero.subtitle}</Text><Text style={s.body}>{t.hero.body}</Text>
 <View style={s.location}><Text>📍</Text><Text style={s.locationText}>{t.hero.location}</Text></View><View style={s.search}><TextInput style={s.input} placeholder={t.hero.searchPlaceholder}/><Pressable style={s.searchBtn}><Text style={s.searchTxt}>⌕ {t.hero.search}</Text></Pressable></View></View>
 <Text style={s.section}>{t.nav.services}</Text><View style={s.grid}>{services.map(x=><Pressable key={x} style={s.card}><Text style={s.service}>{x}</Text></Pressable>)}</View>
 <View style={s.trust}><Text style={s.trustTitle}>✓ {t.how.subtitle}</Text><Text style={s.body}>{t.how.steps[2].body}</Text></View>
 <Text style={s.section}>{t.how.title}</Text>{t.how.steps.map((x,i)=><View style={s.step} key={x.title}><Text style={s.num}>{i+1}</Text><View><Text style={s.stepTitle}>{x.title}</Text><Text style={s.body}>{x.body}</Text></View></View>)}
 <View style={s.provider}><Text style={s.ctaTitle}>{t.provider.title}</Text><Text style={s.body}>{t.provider.body}</Text><Pressable style={s.greenBtn}><Text style={s.white}>{t.provider.cta} →</Text></Pressable></View>
 <View style={s.agent}><Text style={s.ctaTitle}>{t.agent.title}</Text><Text style={s.body}>{t.agent.body}</Text><Pressable style={s.orangeBtn}><Text style={s.white}>{t.agent.cta} →</Text></Pressable></View>
 </ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#fff"},page:{paddingBottom:40},header:{paddingHorizontal:20,paddingVertical:14,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},logo:{fontSize:26,fontWeight:"800",color:"#087A4B"},orange:{color:"#FF6B18"},tag:{fontSize:8,fontWeight:"700"},lang:{backgroundColor:"#F1F6F3",paddingHorizontal:14,paddingVertical:9,borderRadius:12},hero:{margin:12,padding:20,borderRadius:24,backgroundColor:"#F1FAF5"},badge:{fontSize:11,fontWeight:"700",backgroundColor:"#DDF4E7",alignSelf:"flex-start",padding:7,borderRadius:20},title:{fontSize:36,lineHeight:39,fontWeight:"900",color:"#0B2039",marginTop:16},green:{color:"#075C40"},subtitle:{fontSize:16,fontWeight:"700",marginTop:10},body:{color:"#64748B",lineHeight:20,marginTop:5},location:{marginTop:18,backgroundColor:"#fff",padding:14,borderRadius:12,flexDirection:"row",gap:8},locationText:{fontWeight:"600"},search:{marginTop:9,backgroundColor:"#fff",borderRadius:12,flexDirection:"row",alignItems:"center",paddingLeft:12},input:{flex:1,height:50},searchBtn:{backgroundColor:"#FF6B18",padding:13,borderRadius:10,margin:4},searchTxt:{color:"#fff",fontWeight:"700"},section:{fontSize:22,fontWeight:"800",marginHorizontal:20,marginTop:24,marginBottom:12,color:"#0B2039"},grid:{paddingHorizontal:14,flexDirection:"row",flexWrap:"wrap"},card:{width:"25%",padding:6},service:{minHeight:74,textAlign:"center",padding:10,paddingTop:18,borderRadius:16,backgroundColor:"#F6FAF8",fontSize:12,fontWeight:"600"},trust:{margin:20,padding:18,borderRadius:18,backgroundColor:"#FFF6EC"},trustTitle:{fontWeight:"800",color:"#087A4B",fontSize:17},step:{marginHorizontal:20,marginBottom:10,padding:15,borderRadius:16,backgroundColor:"#F8FAF9",flexDirection:"row",gap:14},num:{width:30,height:30,textAlign:"center",paddingTop:5,borderRadius:15,backgroundColor:"#087A4B",color:"#fff",fontWeight:"800"},stepTitle:{fontWeight:"800",fontSize:16},provider:{margin:20,padding:22,borderRadius:22,backgroundColor:"#EAF8F0"},agent:{marginHorizontal:20,padding:22,borderRadius:22,backgroundColor:"#FFF0E6"},ctaTitle:{fontSize:20,fontWeight:"800"},greenBtn:{marginTop:14,backgroundColor:"#087A4B",padding:14,borderRadius:12,alignItems:"center"},orangeBtn:{marginTop:14,backgroundColor:"#FF6B18",padding:14,borderRadius:12,alignItems:"center"},white:{color:"#fff",fontWeight:"800"}});